image: python:latest

stages:
  - testing
  - release

before_script:
  - apt-get update
  - pip install build pytest-xdist

test_gcc:
  stage: testing
  script:
    - python3 -m build --sdist
    - 'tar xvzf dist/ducc0*.tar.gz'
    - 'cd ducc0-* && pip install . && pytest -n auto -q python/test'

test_clang:
  stage: testing
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get install -y clang
    - python3 -m build --sdist
    - 'tar xvzf dist/ducc0*.tar.gz'
    - 'cd ducc0-* && CC=clang CXX=clang++ pip install . && pytest -n auto -q python/test'

release:
  stage: release
  script:
    - python3 -m build --sdist
    - 'mv dist/*.tar.gz .'
  artifacts:
    paths:
      - '*.tar.gz'

pages:
  stage: release
  script:
    - DEBIAN_FRONTEND=noninteractive apt-get install -y doxygen graphviz
    - pip install sphinx pydata-sphinx-theme
    - DUCC0_OPTIMIZATION=none pip install .
    - make -C doc html
    - 'cd src/doc && doxygen Doxyfile && cd ../..'
    - mv doc/build/html public
    - mv src/doc/build/html public/cpp
  artifacts:
    paths:
    - public
  only:
    - ducc0
