#!/bin/bash
HIPSYCL=${HOME}/syclducc/hipSYCL/install
CC=${HIPSYCL}/bin/syclcc CXX=${HIPSYCL}/bin/syclcc DUCC0_CFLAGS=" --hipsycl-targets='cuda:sm_70' -I${HIPSYCL}/include" DUCC0_OPTIMIZATION=native python3 setup.py install --user -f
