# mypy: disable-error-code=overload-overlap
from typing import Optional, Sequence, Union, overload

from .._typing import Complex32Array, Complex64Array, ComplexArray, Float32Array, Float64Array, Shape
from . import experimental as experimental

_Periodicity = Union[float, Sequence[float]]

@overload
def u2nu(*, grid: Complex32Array, coord: Float32Array, forward: bool, epsilon: float, nthreads: int = ..., out: Optional[Complex32Array] = ..., verbosity: int = ..., sigma_min: float = ..., sigma_max: float = ..., periodicity: _Periodicity = ..., fft_order: bool = ...) -> Complex32Array: ...
@overload
def u2nu(*, grid: Complex32Array, coord: Float64Array, forward: bool, epsilon: float, nthreads: int = ..., out: Optional[Complex32Array] = ..., verbosity: int = ..., sigma_min: float = ..., sigma_max: float = ..., periodicity: _Periodicity = ..., fft_order: bool = ...) -> Complex32Array: ...
@overload
def u2nu(*, grid: Complex64Array, coord: Float32Array, forward: bool, epsilon: float, nthreads: int = ..., out: Optional[Complex64Array] = ..., verbosity: int = ..., sigma_min: float = ..., sigma_max: float = ..., periodicity: _Periodicity = ..., fft_order: bool = ...) -> Complex64Array: ...
@overload
def u2nu(*, grid: Complex64Array, coord: Float64Array, forward: bool, epsilon: float, nthreads: int = ..., out: Optional[Complex64Array] = ..., verbosity: int = ..., sigma_min: float = ..., sigma_max: float = ..., periodicity: _Periodicity = ..., fft_order: bool = ...) -> Complex64Array: ...

@overload
def nu2u(*, points: Complex32Array, coord: Float32Array, forward: bool, epsilon: float, nthreads: int = ..., out: Optional[Complex32Array] = ..., verbosity: int = ..., sigma_min: float = ..., sigma_max: float = ..., periodicity: _Periodicity = ..., fft_order: bool = ...) -> Complex32Array: ...
@overload
def nu2u(*, points: Complex32Array, coord: Float64Array, forward: bool, epsilon: float, nthreads: int = ..., out: Optional[Complex32Array] = ..., verbosity: int = ..., sigma_min: float = ..., sigma_max: float = ..., periodicity: _Periodicity = ..., fft_order: bool = ...) -> Complex32Array: ...
@overload
def nu2u(*, points: Complex64Array, coord: Float32Array, forward: bool, epsilon: float, nthreads: int = ..., out: Optional[Complex64Array] = ..., verbosity: int = ..., sigma_min: float = ..., sigma_max: float = ..., periodicity: _Periodicity = ..., fft_order: bool = ...) -> Complex64Array: ...
@overload
def nu2u(*, points: Complex64Array, coord: Float64Array, forward: bool, epsilon: float, nthreads: int = ..., out: Optional[Complex64Array] = ..., verbosity: int = ..., sigma_min: float = ..., sigma_max: float = ..., periodicity: _Periodicity = ..., fft_order: bool = ...) -> Complex64Array: ...

def bestEpsilon(*, ndim: int, singleprec: bool, sigma_min: float = ..., sigma_max: float = ...) -> float: ...

class plan:
    @overload
    def __init__(self, *, nu2u: bool, coord: Float32Array, grid_shape: Shape, epsilon: float, nthreads: int = ..., sigma_min: float = ..., sigma_max: float = ..., periodicity: _Periodicity = ..., fft_order: bool = ...) -> None: ...
    @overload
    def __init__(self, *, nu2u: bool, coord: Float64Array, grid_shape: Shape, epsilon: float, nthreads: int = ..., sigma_min: float = ..., sigma_max: float = ..., periodicity: _Periodicity = ..., fft_order: bool = ...) -> None: ...
    def nu2u(self, *, forward: bool, verbosity: int = ..., points: ComplexArray, out: Optional[ComplexArray] = ...) -> ComplexArray: ...
    def u2nu(self, *, forward: bool, verbosity: int = ..., grid: ComplexArray, out: Optional[ComplexArray] = ...) -> ComplexArray: ...
