# mypy: disable-error-code=overload-overlap
from typing import Optional, Sequence, Union, overload

from ducc0._typing import Complex32Array, Complex64Array, ComplexArray, Float32Array, Float64Array, Shape

_Periodicity = Union[float, Sequence[float]]

@overload
def nu2nu(*, points_in: Complex32Array, coord_in: Float32Array, coord_out: Float32Array, forward: bool, epsilon: float, nthreads: int = ..., points_out: Optional[Complex32Array] = ..., verbosity: int = ..., sigma_min: float = ..., sigma_max: float = ...) -> Complex32Array: ...
@overload
def nu2nu(*, points_in: Complex32Array, coord_in: Float64Array, coord_out: Float64Array, forward: bool, epsilon: float, nthreads: int = ..., points_out: Optional[Complex32Array] = ..., verbosity: int = ..., sigma_min: float = ..., sigma_max: float = ...) -> Complex32Array: ...
@overload
def nu2nu(*, points_in: Complex64Array, coord_in: Float32Array, coord_out: Float32Array, forward: bool, epsilon: float, nthreads: int = ..., points_out: Optional[Complex64Array] = ..., verbosity: int = ..., sigma_min: float = ..., sigma_max: float = ...) -> Complex64Array: ...
@overload
def nu2nu(*, points_in: Complex64Array, coord_in: Float64Array, coord_out: Float64Array, forward: bool, epsilon: float, nthreads: int = ..., points_out: Optional[Complex64Array] = ..., verbosity: int = ..., sigma_min: float = ..., sigma_max: float = ...) -> Complex64Array: ...

class incremental_nu2u:
    def __init__(self, *, npoints_estimate: int = ..., grid_shape: Shape, forward: bool, epsilon: float, nthreads: int = ..., sigma_min: float = ..., sigma_max: float = ..., periodicity: _Periodicity = ..., fft_order: bool = ..., singleprec: bool = ...) -> None: ...
    @overload
    def add_points(self, *, coord: Float32Array, points: Complex32Array) -> None: ...
    @overload
    def add_points(self, *, coord: Float64Array, points: Complex64Array) -> None: ...
    def evaluate_and_reset(self, *, uniform: Optional[ComplexArray] = ...) -> ComplexArray: ...

class incremental_u2nu:
    @overload
    def __init__(self, *, npoints_estimate: int = ..., grid: Complex32Array, forward: bool, epsilon: float, nthreads: int = ..., sigma_min: float = ..., sigma_max: float = ..., periodicity: _Periodicity = ..., fft_order: bool = ...) -> None: ...
    @overload
    def __init__(self, *, npoints_estimate: int = ..., grid: Complex64Array, forward: bool, epsilon: float, nthreads: int = ..., sigma_min: float = ..., sigma_max: float = ..., periodicity: _Periodicity = ..., fft_order: bool = ...) -> None: ...
    @overload
    def get_points(self, *, coord: Float32Array, points: Optional[Complex32Array] = ...) -> Complex32Array: ...
    @overload
    def get_points(self, *, coord: Float64Array, points: Optional[Complex64Array] = ...) -> Complex64Array: ...

class plan3:
    @overload
    def __init__(self, *, coord_in: Float32Array, coord_out: Float32Array, epsilon: float, nthreads: int = ..., sigma_min: float = ..., sigma_max: float = ..., verbosity: int = ...) -> None: ...
    @overload
    def __init__(self, *, coord_in: Float64Array, coord_out: Float64Array, epsilon: float, nthreads: int = ..., sigma_min: float = ..., sigma_max: float = ..., verbosity: int = ...) -> None: ...
    def exec(self, *, forward: bool, points_in: ComplexArray, points_out: Optional[ComplexArray] = ...) -> ComplexArray: ...
    def exec_adjoint(self, *, forward: bool, points_in: ComplexArray, points_out: Optional[ComplexArray] = ...) -> ComplexArray: ...
