# mypy: disable-error-code=overload-overlap
from typing import Optional, overload

from .._typing import Complex32Array, Complex64Array, Float32Array, Float64Array, UInt8Array
from . import experimental as experimental

@overload
def vis2dirty(*, uvw: Float64Array, freq: Float64Array, vis: Complex32Array, wgt: Optional[Float32Array] = ..., npix_x: int = ..., npix_y: int = ..., pixsize_x: float, pixsize_y: float, epsilon: float, do_wgridding: bool = ..., nthreads: int = ..., verbosity: int = ..., mask: Optional[UInt8Array] = ..., flip_u: bool = ..., flip_v: bool = ..., flip_w: bool = ..., divide_by_n: bool = ..., dirty: Optional[Float32Array] = ..., sigma_min: float = ..., sigma_max: float = ..., center_x: float = ..., center_y: float = ..., allow_nshift: bool = ..., double_precision_accumulation: bool = ...) -> Float32Array: ...
@overload
def vis2dirty(*, uvw: Float64Array, freq: Float64Array, vis: Complex64Array, wgt: Optional[Float64Array] = ..., npix_x: int = ..., npix_y: int = ..., pixsize_x: float, pixsize_y: float, epsilon: float, do_wgridding: bool = ..., nthreads: int = ..., verbosity: int = ..., mask: Optional[UInt8Array] = ..., flip_u: bool = ..., flip_v: bool = ..., flip_w: bool = ..., divide_by_n: bool = ..., dirty: Optional[Float64Array] = ..., sigma_min: float = ..., sigma_max: float = ..., center_x: float = ..., center_y: float = ..., allow_nshift: bool = ..., double_precision_accumulation: bool = ...) -> Float64Array: ...

@overload
def dirty2vis(*, uvw: Float64Array, freq: Float64Array, dirty: Float32Array, wgt: Optional[Float32Array] = ..., pixsize_x: float, pixsize_y: float, epsilon: float, do_wgridding: bool = ..., nthreads: int = ..., verbosity: int = ..., mask: Optional[UInt8Array] = ..., flip_u: bool = ..., flip_v: bool = ..., flip_w: bool = ..., divide_by_n: bool = ..., vis: Optional[Complex32Array] = ..., sigma_min: float = ..., sigma_max: float = ..., center_x: float = ..., center_y: float = ..., allow_nshift: bool = ...) -> Complex32Array: ...
@overload
def dirty2vis(*, uvw: Float64Array, freq: Float64Array, dirty: Float64Array, wgt: Optional[Float64Array] = ..., pixsize_x: float, pixsize_y: float, epsilon: float, do_wgridding: bool = ..., nthreads: int = ..., verbosity: int = ..., mask: Optional[UInt8Array] = ..., flip_u: bool = ..., flip_v: bool = ..., flip_w: bool = ..., divide_by_n: bool = ..., vis: Optional[Complex64Array] = ..., sigma_min: float = ..., sigma_max: float = ..., center_x: float = ..., center_y: float = ..., allow_nshift: bool = ...) -> Complex64Array: ...

@overload
def ms2dirty(uvw: Float64Array, freq: Float64Array, ms: Complex32Array, wgt: Optional[Float32Array] = ..., *, npix_x: int, npix_y: int, pixsize_x: float, pixsize_y: float, nu: int = ..., nv: int = ..., epsilon: float, do_wstacking: bool = ..., nthreads: int = ..., verbosity: int = ..., mask: Optional[UInt8Array] = ..., double_precision_accumulation: bool = ...) -> Float32Array: ...
@overload
def ms2dirty(uvw: Float64Array, freq: Float64Array, ms: Complex64Array, wgt: Optional[Float64Array] = ..., *, npix_x: int, npix_y: int, pixsize_x: float, pixsize_y: float, nu: int = ..., nv: int = ..., epsilon: float, do_wstacking: bool = ..., nthreads: int = ..., verbosity: int = ..., mask: Optional[UInt8Array] = ..., double_precision_accumulation: bool = ...) -> Float64Array: ...
@overload
def dirty2ms(uvw: Float64Array, freq: Float64Array, dirty: Float32Array, wgt: Optional[Float32Array] = ..., *, pixsize_x: float, pixsize_y: float, nu: int = ..., nv: int = ..., epsilon: float, do_wstacking: bool = ..., nthreads: int = ..., verbosity: int = ..., mask: Optional[UInt8Array] = ...) -> Complex32Array: ...
@overload
def dirty2ms(uvw: Float64Array, freq: Float64Array, dirty: Float64Array, wgt: Optional[Float64Array] = ..., *, pixsize_x: float, pixsize_y: float, nu: int = ..., nv: int = ..., epsilon: float, do_wstacking: bool = ..., nthreads: int = ..., verbosity: int = ..., mask: Optional[UInt8Array] = ...) -> Complex64Array: ...
