# mypy: disable-error-code="overload-overlap, overload-cannot-match"
# NumPy models some platform dtypes as overlapping; nanobind's long-double
# aliases are NoReturn. The overloads remain useful to Pyright and pybind11.
from typing import Callable, List, Optional, Sequence, Tuple, Type, Union, overload

import numpy as np
from numpy.typing import DTypeLike

from .._typing import Complex32Array, Complex64Array, ComplexArray, Float64Array, Int64Array, LongComplexArray, LongFloatArray, NumericArray, Real32Array, Real64Array, RealArray, Shape, UInt64Array
from . import experimental as experimental

@overload
def vdot(a: NumericArray, b: NumericArray) -> Union[float, complex]: ...
@overload
def vdot(a: Union[float, complex], b: Union[float, complex]) -> Union[float, complex]: ...

@overload
def l2error(a: NumericArray, b: NumericArray) -> float: ...
@overload
def l2error(a: Union[float, complex], b: Union[float, complex]) -> float: ...

@overload
def special_add_at(a: Real32Array, axis: int, index: Int64Array, b: Real32Array) -> Real32Array: ...
@overload
def special_add_at(a: Real64Array, axis: int, index: Int64Array, b: Real64Array) -> Real64Array: ...
@overload
def special_add_at(a: Complex32Array, axis: int, index: Int64Array, b: Complex32Array) -> Complex32Array: ...
@overload
def special_add_at(a: Complex64Array, axis: int, index: Int64Array, b: Complex64Array) -> Complex64Array: ...

def GL_weights(nlat: int, nlon: int) -> Float64Array: ...
def GL_thetas(nlat: int) -> Float64Array: ...

@overload
def transpose(input: Real32Array, output: Real32Array, nthreads: int = ...) -> Real32Array: ...
@overload
def transpose(input: Real64Array, output: Real64Array, nthreads: int = ...) -> Real64Array: ...
@overload
def transpose(input: Complex32Array, output: Complex32Array, nthreads: int = ...) -> Complex32Array: ...
@overload
def transpose(input: Complex64Array, output: Complex64Array, nthreads: int = ...) -> Complex64Array: ...
@overload
def transpose(input: Int64Array, output: Int64Array, nthreads: int = ...) -> Int64Array: ...

@overload
def make_noncritical(input: Real32Array, nthreads: int = ...) -> Real32Array: ...
@overload
def make_noncritical(input: Real64Array, nthreads: int = ...) -> Real64Array: ...
@overload
def make_noncritical(input: Complex32Array, nthreads: int = ...) -> Complex32Array: ...
@overload
def make_noncritical(input: Complex64Array, nthreads: int = ...) -> Complex64Array: ...
@overload
def make_noncritical(input: Union[LongFloatArray, LongComplexArray], nthreads: int = ...) -> NumericArray: ...

@overload
def empty_noncritical(shape: Shape, dtype: Union[np.dtype[np.float32], Type[np.float32]], nthreads: int = ...) -> Real32Array: ...
@overload
def empty_noncritical(shape: Shape, dtype: Union[np.dtype[np.float64], Type[np.float64]], nthreads: int = ...) -> Real64Array: ...
@overload
def empty_noncritical(shape: Shape, dtype: Union[np.dtype[np.complex64], Type[np.complex64]], nthreads: int = ...) -> Complex32Array: ...
@overload
def empty_noncritical(shape: Shape, dtype: Union[np.dtype[np.complex128], Type[np.complex128]], nthreads: int = ...) -> Complex64Array: ...
@overload
def empty_noncritical(shape: Shape, dtype: DTypeLike, nthreads: int = ...) -> NumericArray: ...

class OofaNoise:
    def __init__(self, *, sigmawhite: float, f_knee: float, f_min: float, f_samp: float, slope: float) -> None: ...
    def filterGaussian(self, rnd: Float64Array) -> Float64Array: ...

def scan_kernel(func: Callable[[Sequence[float], Sequence[float]], Sequence[float]], par_min: Sequence[float], par_max: Sequence[float], W: int, M: int, N: int, x0: float, nsamp: int, D: int, mach_eps: float, nthreads: int) -> Tuple[float, List[float]]: ...

@overload
def roll_resize_roll(inp: Real32Array, out: Real32Array, roll_inp: Sequence[int], roll_out: Sequence[int], nthreads: int = ...) -> Real32Array: ...
@overload
def roll_resize_roll(inp: Real64Array, out: Real64Array, roll_inp: Sequence[int], roll_out: Sequence[int], nthreads: int = ...) -> Real64Array: ...
@overload
def roll_resize_roll(inp: Complex32Array, out: Complex32Array, roll_inp: Sequence[int], roll_out: Sequence[int], nthreads: int = ...) -> Complex32Array: ...
@overload
def roll_resize_roll(inp: Complex64Array, out: Complex64Array, roll_inp: Sequence[int], roll_out: Sequence[int], nthreads: int = ...) -> Complex64Array: ...

@overload
def get_deflected_angles(theta: Float64Array, phi0: Float64Array, nphi: UInt64Array, ringstart: UInt64Array, deflect: Real32Array, calc_rotation: bool = ..., res: Optional[Real32Array] = ..., nthreads: int = ..., dphi: Optional[Float64Array] = ...) -> Real32Array: ...
@overload
def get_deflected_angles(theta: Float64Array, phi0: Float64Array, nphi: UInt64Array, ringstart: UInt64Array, deflect: Real64Array, calc_rotation: bool = ..., res: Optional[Real64Array] = ..., nthreads: int = ..., dphi: Optional[Float64Array] = ...) -> Real64Array: ...

@overload
def lensing_rotate(values: Complex32Array, gamma: Real32Array, spin: int, nthreads: int = ...) -> None: ...
@overload
def lensing_rotate(values: Complex64Array, gamma: Real64Array, spin: int, nthreads: int = ...) -> None: ...

def wigner3j_int(l2: int, l3: int, m2: int, m3: int) -> Tuple[int, Float64Array]: ...
def available_hardware_threads() -> int: ...
def thread_pool_size() -> int: ...
def resize_thread_pool(nthreads_new: int) -> None: ...
def preallocate_memory(gbytes: float) -> bool: ...
def set_heap_trim_limit(gbytes: float) -> bool: ...

@overload
def quat2ptg(quat: Real32Array, nthreads: int = ..., out: Optional[Real32Array] = ...) -> Real32Array: ...
@overload
def quat2ptg(quat: Real64Array, nthreads: int = ..., out: Optional[Real64Array] = ...) -> Real64Array: ...
@overload
def ptg2quat(ptg: Real32Array, nthreads: int = ..., out: Optional[Real32Array] = ...) -> Real32Array: ...
@overload
def ptg2quat(ptg: Real64Array, nthreads: int = ..., out: Optional[Real64Array] = ...) -> Real64Array: ...

def print_diagnostics() -> None: ...
def native_vector_lengths() -> Tuple[int, int]: ...
