# mypy: disable-error-code=overload-overlap
from typing import List, Optional, Sequence, Union, overload

from ducc0._typing import Complex32Array, Complex64Array, ComplexArray, Float64Array, NumericArray, Real32Array, Real64Array, RealArray

@overload
def mul_conj(a: Real32Array, b: Complex32Array, out: Optional[Complex32Array] = ...) -> Complex32Array: ...
@overload
def mul_conj(a: Real32Array, b: Complex64Array, out: Optional[Complex64Array] = ...) -> Complex64Array: ...
@overload
def mul_conj(a: Real64Array, b: Complex32Array, out: Optional[Complex64Array] = ...) -> Complex64Array: ...
@overload
def mul_conj(a: Real64Array, b: Complex64Array, out: Optional[Complex64Array] = ...) -> Complex64Array: ...
@overload
def mul_conj(a: Complex32Array, b: Complex32Array, out: Optional[Complex32Array] = ...) -> Complex32Array: ...
@overload
def mul_conj(a: Complex32Array, b: Complex64Array, out: Optional[Complex64Array] = ...) -> Complex64Array: ...
@overload
def mul_conj(a: Complex64Array, b: Complex32Array, out: Optional[Complex64Array] = ...) -> Complex64Array: ...
@overload
def mul_conj(a: Complex64Array, b: Complex64Array, out: Optional[Complex64Array] = ...) -> Complex64Array: ...

@overload
def div_conj(a: Real32Array, b: Complex32Array, out: Optional[Complex32Array] = ...) -> Complex32Array: ...
@overload
def div_conj(a: Real32Array, b: Complex64Array, out: Optional[Complex64Array] = ...) -> Complex64Array: ...
@overload
def div_conj(a: Real64Array, b: Complex32Array, out: Optional[Complex64Array] = ...) -> Complex64Array: ...
@overload
def div_conj(a: Real64Array, b: Complex64Array, out: Optional[Complex64Array] = ...) -> Complex64Array: ...
@overload
def div_conj(a: Complex32Array, b: Complex32Array, out: Optional[Complex32Array] = ...) -> Complex32Array: ...
@overload
def div_conj(a: Complex32Array, b: Complex64Array, out: Optional[Complex64Array] = ...) -> Complex64Array: ...
@overload
def div_conj(a: Complex64Array, b: Complex32Array, out: Optional[Complex64Array] = ...) -> Complex64Array: ...
@overload
def div_conj(a: Complex64Array, b: Complex64Array, out: Optional[Complex64Array] = ...) -> Complex64Array: ...

def LogUnnormalizedGaussProbability(a: NumericArray, b: NumericArray, c: RealArray, nthreads: int = ...) -> float: ...
def LogUnnormalizedGaussProbabilityWithDeriv(a: NumericArray, b: NumericArray, c: RealArray, out: Optional[NumericArray] = ..., nthreads: int = ...) -> List[Union[float, NumericArray]]: ...

@overload
def coupling_matrix_rect(spec: Float64Array, optype: Sequence[int], res: Real32Array, nthreads: int = ..., l_exact: int = ..., l_toeplitz: int = ..., dl_band: int = ...) -> Real32Array: ...
@overload
def coupling_matrix_rect(spec: Float64Array, optype: Sequence[int], res: Real64Array, nthreads: int = ..., l_exact: int = ..., l_toeplitz: int = ..., dl_band: int = ...) -> Real64Array: ...
@overload
def coupling_matrix_rect_new(spec: Float64Array, optype: Sequence[int], res: Real32Array, nthreads: int = ..., l_exact: int = ..., l_toeplitz: int = ..., dl_band: int = ...) -> Real32Array: ...
@overload
def coupling_matrix_rect_new(spec: Float64Array, optype: Sequence[int], res: Real64Array, nthreads: int = ..., l_exact: int = ..., l_toeplitz: int = ..., dl_band: int = ...) -> Real64Array: ...

def pswf0(c: float, x: Float64Array, out: Optional[Float64Array] = ...) -> Float64Array: ...

class PSWF0:
    def __init__(self, c: float) -> None: ...
    def eval(self, x: Float64Array, out: Optional[Float64Array] = ...) -> Float64Array: ...
