# mypy: disable-error-code="overload-overlap, overload-cannot-match"
# NumPy models some platform dtypes as overlapping; nanobind's long-double
# aliases are NoReturn. The overloads remain useful to Pyright and pybind11.
from typing import Optional, Sequence, overload

from ._typing import (
    Complex32Array,
    Complex64Array,
    LongComplexArray,
    LongFloatArray,
    Real32Array,
    Real64Array,
)

_Axes = Optional[Sequence[int]]

@overload
def c2c(a: Real32Array, axes: _Axes = ..., forward: bool = ..., inorm: int = ..., out: Optional[Complex32Array] = ..., nthreads: int = ...) -> Complex32Array: ...
@overload
def c2c(a: Complex32Array, axes: _Axes = ..., forward: bool = ..., inorm: int = ..., out: Optional[Complex32Array] = ..., nthreads: int = ...) -> Complex32Array: ...
@overload
def c2c(a: Real64Array, axes: _Axes = ..., forward: bool = ..., inorm: int = ..., out: Optional[Complex64Array] = ..., nthreads: int = ...) -> Complex64Array: ...
@overload
def c2c(a: Complex64Array, axes: _Axes = ..., forward: bool = ..., inorm: int = ..., out: Optional[Complex64Array] = ..., nthreads: int = ...) -> Complex64Array: ...
@overload
def c2c(a: LongFloatArray, axes: _Axes = ..., forward: bool = ..., inorm: int = ..., out: Optional[LongComplexArray] = ..., nthreads: int = ...) -> LongComplexArray: ...
@overload
def c2c(a: LongComplexArray, axes: _Axes = ..., forward: bool = ..., inorm: int = ..., out: Optional[LongComplexArray] = ..., nthreads: int = ...) -> LongComplexArray: ...

@overload
def r2c(a: Real32Array, axes: _Axes = ..., forward: bool = ..., inorm: int = ..., out: Optional[Complex32Array] = ..., nthreads: int = ...) -> Complex32Array: ...
@overload
def r2c(a: Real64Array, axes: _Axes = ..., forward: bool = ..., inorm: int = ..., out: Optional[Complex64Array] = ..., nthreads: int = ...) -> Complex64Array: ...
@overload
def r2c(a: LongFloatArray, axes: _Axes = ..., forward: bool = ..., inorm: int = ..., out: Optional[LongComplexArray] = ..., nthreads: int = ...) -> LongComplexArray: ...

@overload
def c2r(a: Complex32Array, axes: _Axes = ..., lastsize: int = ..., forward: bool = ..., inorm: int = ..., out: Optional[Real32Array] = ..., nthreads: int = ..., allow_overwriting_input: bool = ...) -> Real32Array: ...
@overload
def c2r(a: Complex64Array, axes: _Axes = ..., lastsize: int = ..., forward: bool = ..., inorm: int = ..., out: Optional[Real64Array] = ..., nthreads: int = ..., allow_overwriting_input: bool = ...) -> Real64Array: ...
@overload
def c2r(a: LongComplexArray, axes: _Axes = ..., lastsize: int = ..., forward: bool = ..., inorm: int = ..., out: Optional[LongFloatArray] = ..., nthreads: int = ..., allow_overwriting_input: bool = ...) -> LongFloatArray: ...

@overload
def r2r_fftpack(a: Real32Array, axes: _Axes, real2hermitian: bool, forward: bool, inorm: int = ..., out: Optional[Real32Array] = ..., nthreads: int = ...) -> Real32Array: ...
@overload
def r2r_fftpack(a: Real64Array, axes: _Axes, real2hermitian: bool, forward: bool, inorm: int = ..., out: Optional[Real64Array] = ..., nthreads: int = ...) -> Real64Array: ...
@overload
def r2r_fftpack(a: LongFloatArray, axes: _Axes, real2hermitian: bool, forward: bool, inorm: int = ..., out: Optional[LongFloatArray] = ..., nthreads: int = ...) -> LongFloatArray: ...

@overload
def r2r_fftw(a: Real32Array, axes: _Axes, forward: bool, inorm: int = ..., out: Optional[Real32Array] = ..., nthreads: int = ...) -> Real32Array: ...
@overload
def r2r_fftw(a: Real64Array, axes: _Axes, forward: bool, inorm: int = ..., out: Optional[Real64Array] = ..., nthreads: int = ...) -> Real64Array: ...
@overload
def r2r_fftw(a: LongFloatArray, axes: _Axes, forward: bool, inorm: int = ..., out: Optional[LongFloatArray] = ..., nthreads: int = ...) -> LongFloatArray: ...

@overload
def separable_hartley(a: Real32Array, axes: _Axes = ..., inorm: int = ..., out: Optional[Real32Array] = ..., nthreads: int = ...) -> Real32Array: ...
@overload
def separable_hartley(a: Real64Array, axes: _Axes = ..., inorm: int = ..., out: Optional[Real64Array] = ..., nthreads: int = ...) -> Real64Array: ...
@overload
def separable_hartley(a: LongFloatArray, axes: _Axes = ..., inorm: int = ..., out: Optional[LongFloatArray] = ..., nthreads: int = ...) -> LongFloatArray: ...

@overload
def genuine_hartley(a: Real32Array, axes: _Axes = ..., inorm: int = ..., out: Optional[Real32Array] = ..., nthreads: int = ...) -> Real32Array: ...
@overload
def genuine_hartley(a: Real64Array, axes: _Axes = ..., inorm: int = ..., out: Optional[Real64Array] = ..., nthreads: int = ...) -> Real64Array: ...
@overload
def genuine_hartley(a: LongFloatArray, axes: _Axes = ..., inorm: int = ..., out: Optional[LongFloatArray] = ..., nthreads: int = ...) -> LongFloatArray: ...

@overload
def separable_fht(a: Real32Array, axes: _Axes = ..., inorm: int = ..., out: Optional[Real32Array] = ..., nthreads: int = ...) -> Real32Array: ...
@overload
def separable_fht(a: Real64Array, axes: _Axes = ..., inorm: int = ..., out: Optional[Real64Array] = ..., nthreads: int = ...) -> Real64Array: ...
@overload
def separable_fht(a: LongFloatArray, axes: _Axes = ..., inorm: int = ..., out: Optional[LongFloatArray] = ..., nthreads: int = ...) -> LongFloatArray: ...

@overload
def genuine_fht(a: Real32Array, axes: _Axes = ..., inorm: int = ..., out: Optional[Real32Array] = ..., nthreads: int = ...) -> Real32Array: ...
@overload
def genuine_fht(a: Real64Array, axes: _Axes = ..., inorm: int = ..., out: Optional[Real64Array] = ..., nthreads: int = ...) -> Real64Array: ...
@overload
def genuine_fht(a: LongFloatArray, axes: _Axes = ..., inorm: int = ..., out: Optional[LongFloatArray] = ..., nthreads: int = ...) -> LongFloatArray: ...

@overload
def dct(a: Real32Array, type: int, axes: _Axes = ..., inorm: int = ..., out: Optional[Real32Array] = ..., nthreads: int = ...) -> Real32Array: ...
@overload
def dct(a: Real64Array, type: int, axes: _Axes = ..., inorm: int = ..., out: Optional[Real64Array] = ..., nthreads: int = ...) -> Real64Array: ...
@overload
def dct(a: LongFloatArray, type: int, axes: _Axes = ..., inorm: int = ..., out: Optional[LongFloatArray] = ..., nthreads: int = ...) -> LongFloatArray: ...

@overload
def dst(a: Real32Array, type: int, axes: _Axes = ..., inorm: int = ..., out: Optional[Real32Array] = ..., nthreads: int = ...) -> Real32Array: ...
@overload
def dst(a: Real64Array, type: int, axes: _Axes = ..., inorm: int = ..., out: Optional[Real64Array] = ..., nthreads: int = ...) -> Real64Array: ...
@overload
def dst(a: LongFloatArray, type: int, axes: _Axes = ..., inorm: int = ..., out: Optional[LongFloatArray] = ..., nthreads: int = ...) -> LongFloatArray: ...

@overload
def convolve_axis(input: Real32Array, output: Real32Array, axis: int, kernel: Real32Array, nthreads: int = ...) -> Real32Array: ...
@overload
def convolve_axis(input: Real64Array, output: Real64Array, axis: int, kernel: Real64Array, nthreads: int = ...) -> Real64Array: ...
@overload
def convolve_axis(input: Complex32Array, output: Complex32Array, axis: int, kernel: Complex32Array, nthreads: int = ...) -> Complex32Array: ...
@overload
def convolve_axis(input: Complex64Array, output: Complex64Array, axis: int, kernel: Complex64Array, nthreads: int = ...) -> Complex64Array: ...
@overload
def convolve_axis(input: LongFloatArray, output: LongFloatArray, axis: int, kernel: LongFloatArray, nthreads: int = ...) -> LongFloatArray: ...
@overload
def convolve_axis(input: LongComplexArray, output: LongComplexArray, axis: int, kernel: LongComplexArray, nthreads: int = ...) -> LongComplexArray: ...

def good_size(n: int, real: bool = ...) -> int: ...
