from typing import Literal, Optional, TypedDict

from ._typing import Float64Array, Int64Array, IntegerArray, RealArray, UInt64Array

class _SHTInfo(TypedDict):
    theta: Float64Array
    phi0: Float64Array
    nphi: UInt64Array
    ringstart: UInt64Array

class Healpix_Base:
    def __init__(self, nside: int, scheme: Literal["RING", "NEST", "NESTED"]) -> None: ...
    def order(self) -> int: ...
    def nside(self) -> int: ...
    def npix(self) -> int: ...
    def scheme(self) -> Literal["RING", "NEST"]: ...
    def pix_area(self) -> float: ...
    def max_pixrad(self) -> float: ...
    def pix2ang(self, pix: IntegerArray, nthreads: int = ..., out: Optional[Float64Array] = ...) -> Float64Array: ...
    def ang2pix(self, ang: RealArray, nthreads: int = ..., out: Optional[Int64Array] = ...) -> Int64Array: ...
    def pix2vec(self, pix: IntegerArray, nthreads: int = ..., out: Optional[Float64Array] = ...) -> Float64Array: ...
    def vec2pix(self, vec: RealArray, nthreads: int = ..., out: Optional[Int64Array] = ...) -> Int64Array: ...
    def pix2xyf(self, pix: IntegerArray, nthreads: int = ..., out: Optional[Int64Array] = ...) -> Int64Array: ...
    def xyf2pix(self, xyf: IntegerArray, nthreads: int = ..., out: Optional[Int64Array] = ...) -> Int64Array: ...
    def neighbors(self, pix: IntegerArray, nthreads: int = ..., out: Optional[Int64Array] = ...) -> Int64Array: ...
    def ring2nest(self, ring: IntegerArray, nthreads: int = ..., out: Optional[Int64Array] = ...) -> Int64Array: ...
    def nest2ring(self, nest: IntegerArray, nthreads: int = ..., out: Optional[Int64Array] = ...) -> Int64Array: ...
    def query_disc(self, ptg: RealArray, radius: float) -> Int64Array: ...
    def sht_info(self) -> _SHTInfo: ...
    def __repr__(self) -> str: ...

def ang2vec(ang: RealArray, nthreads: int = ..., out: Optional[Float64Array] = ...) -> Float64Array: ...
def vec2ang(vec: RealArray, nthreads: int = ..., out: Optional[Float64Array] = ...) -> Float64Array: ...
def v_angle(v1: RealArray, v2: RealArray, nthreads: int = ..., out: Optional[Float64Array] = ...) -> Float64Array: ...
