from typing import Optional, overload

from ._typing import Float32Array, Float64Array

class PointingProvider:
    def __init__(self, t0: float, freq: float, quat: Float64Array, nthreads: int = ...) -> None: ...
    @overload
    def get_rotated_quaternions(self, t0: float, freq: float, rot: Float64Array, nval: int, rot_left: bool = ...) -> Float64Array: ...
    @overload
    def get_rotated_quaternions(self, t0: float, freq: float, rot: Float64Array, *, rot_left: bool = ..., out: Float32Array) -> Float32Array: ...
    @overload
    def get_rotated_quaternions(self, t0: float, freq: float, rot: Float64Array, *, rot_left: bool = ..., out: Float64Array) -> Float64Array: ...
