from typing import List, overload

from ._typing import Complex32Array, Complex64Array, Float32Array, Float64Array

class ConvolverPlan:
    @overload
    def __init__(self, lmax: int, kmax: int, npoints: int, sigma_min: float, sigma_max: float, epsilon: float, nthreads: int = ...) -> None: ...
    @overload
    def __init__(self, lmax: int, kmax: int, sigma: float, epsilon: float, nthreads: int = ...) -> None: ...
    @overload
    def __init__(self, lmax: int, kmax: int, *, epsilon: float, npoints: int = ..., sigma_min: float = ..., sigma_max: float = ..., nthreads: int = ...) -> None: ...
    def Ntheta(self) -> int: ...
    def Nphi(self) -> int: ...
    def Npsi(self) -> int: ...
    def getPatchInfo(self, theta_lo: float, theta_hi: float, phi_lo: float, phi_hi: float) -> List[int]: ...
    def getPlane(self, slm: Complex64Array, blm: Complex64Array, mbeam: int, planes: Complex64Array) -> None: ...
    def prepPsi(self, subcube: Complex64Array) -> None: ...
    def deprepPsi(self, subcube: Complex64Array) -> None: ...
    def interpol(self, cube: Complex64Array, itheta0: int, iphi0: int, theta: Float64Array, phi: Float64Array, psi: Float64Array, signal: Complex64Array) -> None: ...
    def deinterpol(self, cube: Complex64Array, itheta0: int, iphi0: int, theta: Float64Array, phi: Float64Array, psi: Float64Array, signal: Complex64Array) -> None: ...
    def updateSlm(self, slm: Complex64Array, blm: Complex64Array, mbeam: int, planes: Complex64Array) -> None: ...

class ConvolverPlan_f:
    @overload
    def __init__(self, lmax: int, kmax: int, npoints: int, sigma_min: float, sigma_max: float, epsilon: float, nthreads: int = ...) -> None: ...
    @overload
    def __init__(self, lmax: int, kmax: int, sigma: float, epsilon: float, nthreads: int = ...) -> None: ...
    @overload
    def __init__(self, lmax: int, kmax: int, *, epsilon: float, npoints: int = ..., sigma_min: float = ..., sigma_max: float = ..., nthreads: int = ...) -> None: ...
    def Ntheta(self) -> int: ...
    def Nphi(self) -> int: ...
    def Npsi(self) -> int: ...
    def getPatchInfo(self, theta_lo: float, theta_hi: float, phi_lo: float, phi_hi: float) -> List[int]: ...
    def getPlane(self, slm: Complex32Array, blm: Complex32Array, mbeam: int, planes: Complex32Array) -> None: ...
    def prepPsi(self, subcube: Complex32Array) -> None: ...
    def deprepPsi(self, subcube: Complex32Array) -> None: ...
    def interpol(self, cube: Complex32Array, itheta0: int, iphi0: int, theta: Float32Array, phi: Float32Array, psi: Float32Array, signal: Complex32Array) -> None: ...
    def deinterpol(self, cube: Complex32Array, itheta0: int, iphi0: int, theta: Float32Array, phi: Float32Array, psi: Float32Array, signal: Complex32Array) -> None: ...
    def updateSlm(self, slm: Complex32Array, blm: Complex32Array, mbeam: int, planes: Complex32Array) -> None: ...

class Interpolator:
    @overload
    def __init__(self, sky: Complex64Array, beam: Complex64Array, separate: bool, lmax: int, kmax: int, npoints: int, sigma_min: float, sigma_max: float, epsilon: float, nthreads: int = ...) -> None: ...
    @overload
    def __init__(self, lmax: int, kmax: int, ncomp: int, npoints: int, sigma_min: float, sigma_max: float, epsilon: float, nthreads: int = ...) -> None: ...
    @overload
    def __init__(self, sky: Complex64Array, beam: Complex64Array, separate: bool, lmax: int, kmax: int, epsilon: float, ofactor: float = ..., nthreads: int = ...) -> None: ...
    @overload
    def __init__(self, lmax: int, kmax: int, ncomp: int, epsilon: float, ofactor: float = ..., nthreads: int = ...) -> None: ...
    @overload
    def __init__(self, sky: Complex64Array, beam: Complex64Array, separate: bool, lmax: int, kmax: int, *, epsilon: float, npoints: int = ..., sigma_min: float = ..., sigma_max: float = ..., nthreads: int = ...) -> None: ...
    @overload
    def __init__(self, lmax: int, kmax: int, ncomp: int, *, epsilon: float, npoints: int = ..., sigma_min: float = ..., sigma_max: float = ..., nthreads: int = ...) -> None: ...
    def interpol(self, ptg: Float64Array) -> Complex64Array: ...
    def deinterpol(self, ptg: Float64Array, data: Complex64Array) -> None: ...
    def getSlm(self, beam: Complex64Array) -> Complex64Array: ...

class Interpolator_f:
    @overload
    def __init__(self, sky: Complex32Array, beam: Complex32Array, separate: bool, lmax: int, kmax: int, npoints: int, sigma_min: float, sigma_max: float, epsilon: float, nthreads: int = ...) -> None: ...
    @overload
    def __init__(self, lmax: int, kmax: int, ncomp: int, npoints: int, sigma_min: float, sigma_max: float, epsilon: float, nthreads: int = ...) -> None: ...
    @overload
    def __init__(self, sky: Complex32Array, beam: Complex32Array, separate: bool, lmax: int, kmax: int, epsilon: float, ofactor: float = ..., nthreads: int = ...) -> None: ...
    @overload
    def __init__(self, lmax: int, kmax: int, ncomp: int, epsilon: float, ofactor: float = ..., nthreads: int = ...) -> None: ...
    @overload
    def __init__(self, sky: Complex32Array, beam: Complex32Array, separate: bool, lmax: int, kmax: int, *, epsilon: float, npoints: int = ..., sigma_min: float = ..., sigma_max: float = ..., nthreads: int = ...) -> None: ...
    @overload
    def __init__(self, lmax: int, kmax: int, ncomp: int, *, epsilon: float, npoints: int = ..., sigma_min: float = ..., sigma_max: float = ..., nthreads: int = ...) -> None: ...
    def interpol(self, ptg: Float32Array) -> Complex32Array: ...
    def deinterpol(self, ptg: Float32Array, data: Complex32Array) -> None: ...
    def getSlm(self, beam: Complex32Array) -> Complex32Array: ...
