# mypy: disable-error-code=overload-overlap
from typing import Literal, Optional, Tuple, overload

from .._typing import Complex32Array, Complex64Array, ComplexArray, Float32Array, Float64Array, Int64Array, Real32Array, Real64Array, RealArray, UInt64Array

_Mode = Literal["STANDARD", "GRAD_ONLY", "DERIV1"]

def alm2leg(*, alm: ComplexArray, lmax: int, theta: Float64Array, spin: int = ..., mval: Optional[Int64Array] = ..., mstart: Optional[UInt64Array] = ..., lstride: int = ..., nthreads: int = ..., leg: Optional[ComplexArray] = ..., mode: _Mode = ..., theta_interpol: bool = ...) -> ComplexArray: ...
def alm2leg_deriv1(*, alm: ComplexArray, lmax: int, theta: Float64Array, mval: Optional[Int64Array] = ..., mstart: Optional[UInt64Array] = ..., lstride: int = ..., nthreads: int = ..., leg: Optional[ComplexArray] = ..., theta_interpol: bool = ...) -> ComplexArray: ...
def leg2alm(*, leg: ComplexArray, lmax: int, theta: Float64Array, spin: int = ..., mval: Optional[Int64Array] = ..., mstart: Optional[UInt64Array] = ..., lstride: int = ..., nthreads: int = ..., alm: Optional[ComplexArray] = ..., mode: _Mode = ..., theta_interpol: bool = ...) -> ComplexArray: ...

def map2leg(*, map: RealArray, nphi: UInt64Array, phi0: Float64Array, ringstart: UInt64Array, ringfactor: Optional[Float64Array] = ..., mmax: int, pixstride: int = ..., nthreads: int = ..., leg: Optional[ComplexArray] = ...) -> ComplexArray: ...
def leg2map(*, leg: ComplexArray, nphi: UInt64Array, phi0: Float64Array, ringstart: UInt64Array, ringfactor: Optional[Float64Array] = ..., pixstride: int = ..., nthreads: int = ..., map: Optional[RealArray] = ...) -> RealArray: ...

def synthesis(*, alm: ComplexArray, theta: Float64Array, lmax: int, mstart: Optional[UInt64Array] = ..., nphi: UInt64Array, phi0: Float64Array, ringstart: UInt64Array, ringfactor: Optional[Float64Array] = ..., spin: int, lstride: int = ..., pixstride: int = ..., nthreads: int = ..., map: Optional[RealArray] = ..., mmax: Optional[int] = ..., mode: _Mode = ..., theta_interpol: bool = ...) -> RealArray: ...
def synthesis_deriv1(*, alm: ComplexArray, theta: Float64Array, lmax: int, mstart: Optional[UInt64Array] = ..., nphi: UInt64Array, phi0: Float64Array, ringstart: UInt64Array, ringfactor: Optional[Float64Array] = ..., lstride: int = ..., pixstride: int = ..., nthreads: int = ..., map: Optional[RealArray] = ..., mmax: Optional[int] = ..., theta_interpol: bool = ...) -> RealArray: ...
@overload
def synthesis_2d(*, alm: Complex32Array, spin: int, lmax: int, geometry: str, ntheta: Optional[int] = ..., nphi: Optional[int] = ..., mmax: Optional[int] = ..., nthreads: int = ..., map: Optional[Real32Array] = ..., mode: _Mode = ..., phi0: float = ..., ringfactor: Optional[Float64Array] = ..., mstart: Optional[UInt64Array] = ..., lstride: int = ...) -> Real32Array: ...
@overload
def synthesis_2d(*, alm: Complex64Array, spin: int, lmax: int, geometry: str, ntheta: Optional[int] = ..., nphi: Optional[int] = ..., mmax: Optional[int] = ..., nthreads: int = ..., map: Optional[Real64Array] = ..., mode: _Mode = ..., phi0: float = ..., ringfactor: Optional[Float64Array] = ..., mstart: Optional[UInt64Array] = ..., lstride: int = ...) -> Real64Array: ...
def synthesis_2d_deriv1(*, alm: ComplexArray, lmax: int, geometry: str, ntheta: Optional[int] = ..., nphi: Optional[int] = ..., mmax: Optional[int] = ..., nthreads: int = ..., map: Optional[RealArray] = ..., phi0: float = ..., ringfactor: Optional[Float64Array] = ..., mstart: Optional[UInt64Array] = ..., lstride: int = ...) -> RealArray: ...
def synthesis_general(*, alm: ComplexArray, spin: int, lmax: int, loc: Float64Array, epsilon: float, mstart: Optional[UInt64Array] = ..., lstride: int = ..., mmax: Optional[int] = ..., nthreads: int = ..., map: Optional[RealArray] = ..., sigma_min: float = ..., sigma_max: float = ..., mode: _Mode = ..., verbose: bool = ...) -> RealArray: ...

def adjoint_synthesis(*, map: RealArray, theta: Float64Array, lmax: int, mstart: Optional[UInt64Array] = ..., nphi: UInt64Array, phi0: Float64Array, ringstart: UInt64Array, ringfactor: Optional[Float64Array] = ..., spin: int, lstride: int = ..., pixstride: int = ..., nthreads: int = ..., alm: Optional[ComplexArray] = ..., mmax: Optional[int] = ..., mode: _Mode = ..., theta_interpol: bool = ...) -> ComplexArray: ...
def adjoint_synthesis_2d(*, map: RealArray, spin: int, lmax: int, geometry: str, mmax: Optional[int] = ..., nthreads: int = ..., alm: Optional[ComplexArray] = ..., mode: _Mode = ..., phi0: float = ..., ringfactor: Optional[Float64Array] = ..., mstart: Optional[UInt64Array] = ..., lstride: int = ...) -> ComplexArray: ...
def adjoint_synthesis_general(*, map: RealArray, spin: int, lmax: int, loc: Float64Array, epsilon: float, mstart: Optional[UInt64Array] = ..., lstride: int = ..., mmax: Optional[int] = ..., nthreads: int = ..., alm: Optional[ComplexArray] = ..., sigma_min: float = ..., sigma_max: float = ..., mode: _Mode = ..., verbose: bool = ...) -> ComplexArray: ...

def pseudo_analysis(*, map: RealArray, theta: Float64Array, lmax: int, mstart: Optional[UInt64Array] = ..., nphi: UInt64Array, phi0: Float64Array, ringstart: UInt64Array, ringfactor: Optional[Float64Array] = ..., spin: int, lstride: int = ..., pixstride: int = ..., nthreads: int = ..., alm: Optional[ComplexArray] = ..., maxiter: int, epsilon: float, mmax: Optional[int] = ..., theta_interpol: bool = ..., alm_contains_initial_guess: bool = ...) -> Tuple[ComplexArray, int, int, float, float]: ...
@overload
def analysis_2d(*, map: Real32Array, spin: int, lmax: int, geometry: str, mmax: Optional[int] = ..., nthreads: int = ..., alm: Optional[Complex32Array] = ..., phi0: float = ..., ringfactor: Optional[Float64Array] = ..., mstart: Optional[UInt64Array] = ..., lstride: int = ...) -> Complex32Array: ...
@overload
def analysis_2d(*, map: Real64Array, spin: int, lmax: int, geometry: str, mmax: Optional[int] = ..., nthreads: int = ..., alm: Optional[Complex64Array] = ..., phi0: float = ..., ringfactor: Optional[Float64Array] = ..., mstart: Optional[UInt64Array] = ..., lstride: int = ...) -> Complex64Array: ...
def pseudo_analysis_general(*, lmax: int, map: RealArray, loc: Float64Array, spin: int, nthreads: int = ..., maxiter: int, epsilon: float, sigma_min: float = ..., sigma_max: float = ..., mstart: Optional[UInt64Array] = ..., lstride: int = ..., mmax: Optional[int] = ..., alm: Optional[ComplexArray] = ..., verbose: bool = ..., alm_contains_initial_guess: bool = ...) -> Tuple[ComplexArray, int, int, float, float]: ...
def adjoint_analysis_2d(*, alm: ComplexArray, spin: int, lmax: int, geometry: str, ntheta: Optional[int] = ..., nphi: Optional[int] = ..., mmax: Optional[int] = ..., nthreads: int = ..., map: Optional[RealArray] = ..., phi0: float = ..., ringfactor: Optional[Float64Array] = ..., mstart: Optional[UInt64Array] = ..., lstride: int = ...) -> RealArray: ...

def get_gridweights(geometry: str, ntheta: int) -> Float64Array: ...
def maximum_safe_l(geometry: str, ntheta: int) -> int: ...
def rotate_alm(alm: ComplexArray, lmax: int, psi: float, theta: float, phi: float, nthreads: int = ..., *, mmax_in: Optional[int] = ..., mmax_out: Optional[int] = ..., out: Optional[ComplexArray] = ...) -> ComplexArray: ...

class sharpjob_d:
    def __init__(self) -> None: ...
    def set_nthreads(self, nthreads: int) -> None: ...
    def set_gauss_geometry(self, ntheta: int, nphi: int) -> None: ...
    def set_healpix_geometry(self, nside: int) -> None: ...
    def set_fejer1_geometry(self, ntheta: int, nphi: int) -> None: ...
    def set_fejer2_geometry(self, ntheta: int, nphi: int) -> None: ...
    def set_cc_geometry(self, ntheta: int, nphi: int) -> None: ...
    def set_dh_geometry(self, ntheta: int, nphi: int) -> None: ...
    def set_mw_geometry(self, ntheta: int, nphi: int) -> None: ...
    def set_triangular_alm_info(self, lmax: int, mmax: int) -> None: ...
    def n_alm(self) -> int: ...
    def alm2map(self, alm: Complex64Array) -> Float64Array: ...
    def alm2map_adjoint(self, map: Float64Array) -> Complex64Array: ...
    def map2alm(self, map: Float64Array) -> Complex64Array: ...
    def alm2map_spin(self, alm: Complex64Array, spin: int) -> Float64Array: ...
    def map2alm_spin(self, map: Float64Array, spin: int) -> Complex64Array: ...
    def __repr__(self) -> str: ...

from . import experimental as experimental
