name: ducc-tests
on: [workflow_dispatch]
jobs:
  test-macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --user --upgrade setuptools pybind11 pytest numpy scipy
      - run: DUCC0_OPTIMIZATION=portable python -m pip install --user .
      - run: python -m pytest python/test -x
  test-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --user --upgrade setuptools pybind11 pytest numpy scipy
      - run: python -m pip install --user .
      - run: python -m pytest python/test -x
  test-intel:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: python -m pip install --user --upgrade setuptools pybind11 pytest scipy
      - run: wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
      - run: sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
      - run: sudo add-apt-repository "deb https://apt.repos.intel.com/oneapi all main"
      - run: sudo apt update
      - run: sudo apt install intel-oneapi-compiler-dpcpp-cpp
      - run: |
          source /opt/intel/oneapi/setvars.sh intel64
          CC=icx CXX=icpx python3 -m pip install --user .
          python -m pytest python/test -x
